trigger:
  branches:
    include:
    - main
pool:
  vmImage: ubuntu-latest
stages:
- stage: validate
  jobs:
  - job: validate
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: 'install'
      inputs:
        terraformVersion: '0.12.3'
    - task: TerraformTaskV1@0
      displayName: 'init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Deploytf'
        backendAzureRmResourceGroupName: 'tamopstf01'
        backendAzureRmStorageAccountName: 'tamopstf01'
        backendAzureRmContainerName: 'tfstatedevops'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTaskV1@0
      displayName: 'validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
- stage: deploy
  jobs:
  - deployment: deploy_terraform
    continueOnError: false
    environment:
      name: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
            inputs:
              repository: self
          - task: TerraformInstaller@0
            displayName: 'install'
            inputs:
              terraformVersion: '0.12.3'
          - task: TerraformTaskV1@0
            displayName: 'init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Deploytf'
              backendAzureRmResourceGroupName: 'tamopstf01'
              backendAzureRmStorageAccountName: 'tamopstf01'
              backendAzureRmContainerName: 'tfstatedevops'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV1@0
            displayName: 'plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Deploytf'
          - task: TerraformTaskV1@0
            displayName: 'apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Deploytf'

